export const COUNTRIES = [
  "Argentina",
  "Bolivia",
  "Brasil",
  "Chile",
  "Colombia",
  "Costa Rica",
  "Cuba",
  "Ecuador",
  "El Salvador",
  "España",
  "Estados Unidos",
  "Guatemala",
  "Honduras",
  "México",
  "Nicaragua",
  "Panamá",
  "Paraguay",
  "Perú",
  "Puerto Rico",
  "República Dominicana",
  "Uruguay",
  "Venezuela",
  // Otros países
  "Alemania",
  "Andorra",
  "Arabia Saudita",
  "Argelia",
  "Australia",
  "Austria",
  "Bélgica",
  "Canadá",
  "China",
  "Corea del Sur",
  "Dinamarca",
  "Egipto",
  "Emiratos Árabes Unidos",
  "Filipinas",
  "Finlandia",
  "Francia",
  "Grecia",
  "India",
  "Indonesia",
  "Irlanda",
  "Islandia",
  "Israel",
  "Italia",
  "Japón",
  "Marruecos",
  "Noruega",
  "Nueva Zelanda",
  "Países Bajos",
  "Polonia",
  "Portugal",
  "Reino Unido",
  "Rusia",
  "Singapur",
  "Sudáfrica",
  "Suecia",
  "Suiza",
  "Tailandia",
  "Turquía",
] as const;

export type Country = typeof COUNTRIES[number];
